[project]
name = "productividad-vs-social-media"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "polars>=1.30.0",
    "prompt-toolkit>=3.0.51",
    "seaborn>=0.13.2",
]
